spring.application.name=WellthAppBack

#db
spring.datasource.url=jdbc:mysql://localhost:3306/wellth?createDatabaseIfNotExist=true&useSSL=false&Unicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=h


#orm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql
spring.jpa.hibernate.dialect : org.hibernate.dialect.MYSQL5Dialect

spring.ai.openai.api-key=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

openai.key4Chat = pascencore
